---
- name: Instalar y asegurar que Apache esté ejecutándose
  hosts: all
  become: yes

  tasks:
    - name: Actualizar el caché de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Asegurarse de que Apache esté iniciado y habilitado
      service:
        name: apache2
        state: started
        enabled: yes
